kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: build and push docker image
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker build --no-cache -t casperfrost/todoistsorter:dev .
    - docker push
  

#- name: greeting
#  image: python:3.8-alpine
#  commands:
#  - echo hello
#  - echo world
