kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: casperfrost/todoistsorter
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: dev
    dry_run: false
